version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Security updates should be prioritized
    security-updates-only: false
    versioning-strategy: "lockfile-only"
    # Group updates together
    groups:
      security:
        patterns:
          - "*"
        update-types:
          - "security"
      # Group patch & minor updates together
      minor-patches:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Keep major updates separate as they might break things
      major:
        patterns:
          - "*"
        update-types:
          - "major"
    # Ignore certain dependencies that need manual updates
    ignore:
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "torchvision"
        update-types: ["version-update:semver-major"]
    # Require review from security team
    reviewers:
      - "admarble"
    # Assign to maintainers
    assignees:
      - "admarble"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Security updates should be prioritized
    security-updates-only: false
    # Group updates together
    groups:
      security:
        patterns:
          - "*"
        update-types:
          - "security"
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Require review from maintainers
    reviewers:
      - "admarble"
    # Assign to maintainers
    assignees:
      - "admarble" 