video_processing:
  level: INFO
  max_bytes: 20971520  # 20MB
  backup_count: 10
  format: "%(asctime)s - %(levelname)s - %(message)s"
  rotation_when: D
  rotation_interval: 1
  use_console: true

error:
  level: ERROR
  max_bytes: 52428800  # 50MB
  backup_count: 20
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(exc_info)s"
  rotation_when: midnight
  rotation_interval: 1
  use_console: true

system:
  level: INFO
  max_bytes: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  rotation_when: H
  rotation_interval: 12
  use_console: true

access:
  level: INFO
  max_bytes: 15728640  # 15MB
  backup_count: 7
  format: "%(asctime)s - %(message)s"
  rotation_when: D
  rotation_interval: 1
  use_console: false 