name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

permissions:
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety pip-audit

    - name: Run Bandit
      continue-on-error: true
      run: |
        bandit -r src/ -f json -o bandit-results.json
        bandit -r src/ -f txt -o bandit-results.txt || true

    - name: Check dependencies with Safety
      continue-on-error: true
      run: |
        safety check -r requirements.txt --output json > safety-results.json
        safety check -r requirements.txt || true

    - name: Check dependencies with pip-audit
      continue-on-error: true
      run: |
        pip-audit -r requirements.txt -f json > pip-audit-results.json || true

    - name: Run Snyk to check for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

    - name: Upload security scan results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-results
        path: |
          bandit-results.json
          bandit-results.txt
          safety-results.json
          pip-audit-results.json 